services:
  db:
    image: mariadb:10.10
    container_name: aq-connecta-db
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MARIADB_DATABASE: ${MYSQL_DB:-aqConnecta}
      MARIADB_USER: ${MYSQL_USER:-aq_user}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-aq_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      # Use CMD-SHELL para poder usar $$ (escapa para avaliar dentro do container)
      test: [ "CMD-SHELL", "mariadb -h 127.0.0.1 -uroot -p${DB_ROOT_PASSWORD:-rootpass} -e 'SELECT 1' >/dev/null 2>&1 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.8.1
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    # Constrói sua imagem Java (Dockerfile multi-stage com Maven que te passei)
    build:
      context: https://github.com/AQConnecta/AQConnecta-back.git#master
      dockerfile: Dockerfile
      # Se quiser forçar profile no build (opcional):
      args:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    container_name: aqconnecta-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      PORT: ${BACKEND_HTTP_PORT}
    ports:
      - "${BACKEND_HTTP_PORT}:8080" # host:container
    restart: unless-stopped

volumes:
  mariadb_data:
